# Site settings
url: "https://www.solaris-spa.com"
baseurl: "/"
title: "Solaris Massage Spa"
description: "Looking for high quality massage at a great price in Dubai? Visit our spa on Airport Road and let our skilled massage therapists help you to relax and unwind from 120 AED/Hr. VIP rooms with en-suite showers. Moroccan Bath, Steam Room, Jacuzzi. Easy parking outside."
description_b: "Massage Spa and Relaxation Therapy in Dubai, United Arab Emirates (UAE), massage, moroccan bath, steam room, jacuzzi"
keywords: "Massage, Spa, Relaxation, Therapy, Wellness, Jacuzzi, Bath, Moroccan Bath, Steam Room, Dubai, UAE, United Arab Emirates, VIP, Executive"

logo_title: "Solaris"
logo_caption: "Massage & Relaxation Center"

organisation: "Solaris Massage & Relaxation Center"
organisation_address: "20 Airport Road, Al Garhoud, Dubai"
organisation_email: "info@solaris-spa.com"
organisation_phone: "+971 58 658 2958"

social_url_instagram: "https://www.instagram.com/solaris.dubai/"

google_analytics: "UA-145708486-1"
google_analytics_4: "UA-145708486-1"
booking_url: "/book"

discount_enable: false
discount_pct: "20"
discount_text: <i class="fas fa-tags"></i> Online Special offer from 120 AED!
#discount_text: <i class="fas fa-holly-berry"></i> Winter special offer from 120 AED! <i class="fas fa-gifts"></i>


collections:
  - staff_members

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
permalink: pretty

sass:
  style: compressed

host: 0.0.0.0