# Site settings
url: "https://www.solaris-spa.com"
baseurl: "/"
title: "Solaris Massage & Relaxation Center"
description: "Massage Spa and Relaxation Therapy in Dubai, United Arab Emirates (UAE), Massage Beds, Moroccan Bath, Steam Room, Jacuzzi"
keywords: "Massage, Spa, Relaxation, Therapy, Wellness, Jacuzzi, Bath, Moroccan Bath, Steam Room, Dubai, UAE, United Arab Emirates"

logo_title: "Solaris"
logo_caption: "Massage & Relaxation Center"

organisation: "Solaris Massage & Relaxation Center"
organisation_address: "20 Airport Road, Al Garhoud, Dubai"
organisation_email: "info@solaris-spa.com"
organisation_phone: "+971 58 658 2958"

google_analytics: "UA-145708486-1"
booking_url: "https://www.fresha.com/providers/solaris-spa"

collections:
  - staff_members

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

host: 0.0.0.0