---
-
    name: Full Body Massage & Oil | Lotion
    price60: 200
    price90: 280
    price120: 360
    price60d: 130
    price90d: 180
    price120d: 240
-
    name: Full Body Massage & Hot Oil | Hot Stones
    price60: 230
    price90: 320
    price120: 410
    price60d: 150
    price90d: 210
    price120d: 270
-
    name: Water Jet Bath & Massage
    price60: 300
    price90: 420
    price120: 540
    price60d: 200
    price90d: 280
    price120d: 360
-
    name: Moroccan Bath & Massage
    price60: 300
    price90: 420
    price120: 540
    price60d: 200
    price90d: 280
    price120d: 360
-
    name: 4 Hands Full Body Massage & Oil | Lotion
    price60: 400
    price90: 560
    price120: 720
    price60d: 260
    price90d: 370
    price120d: 480
-
    name: 4 Hands Full Body Massage & Hot Oil | Hot Stones
    price60: 430
    price90: 600
    price120: 770
    price60d: 280
    price90d: 400
    price120d: 510
-
    name: 4 Hands Water Jet Bath & Massage
    price60: 500
    price90: 700
    price120: 900
    price60d: 330
    price90d: 460
    price120d: 590
-
    name: 4 Hands Moroccan Bath & Massage
    price60: 500
    price90: 700
    price120: 900
    price60d: 330
    price90d: 460
    price120d: 590
