---
-
    name: Full Body Massage
    price60: 150
    price90: 200
    price120: 230
    price60d: 100
    price90d: 130
    price120d: 150
-
    name: Full Body Massage with Oil, Aromatherapy or Hot Stones
    price60: 180
    price90: 230
    price120: 270
    price60d: 120
    price90d: 160
    price120d: 180
-
    name: Full Body Massage with Water Jet Bath
    price60: 300
    price90: 390
    price120: 450
    price60d: 200
    price90d: 260
    price120d: 300
-
    name: Full Body Massage with Moroccan Bath
    price60: 300
    price90: 390
    price120: 450
    price60d: 200
    price90d: 260
    price120d: 300
-
    name: 4 Hands Full Body Massage
    price60: 300
    price90: 390
    price120: 450
    price60d: 200
    price90d: 260
    price120d: 300
-
    name: 4 Hands Full Body Massage with Oil, Aromatherapy or Hot Stones
    price60: 330
    price90: 430
    price120: 500
    price60d: 220
    price90d: 290
    price120d: 330
-
    name: 4 Hands Full Body Massage with Water Jet Bath
    price60: 450
    price90: 590
    price120: 680
    price60d: 300
    price90d: 390
    price120d: 450
-
    name: 4 Hands Full Body Massage with Moroccan Bath
    price60: 450
    price90: 590
    price120: 680
    price60d: 300
    price90d: 390
    price120d: 450
